apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
  - image: post2log-server
    context: server 
  - image: post2log-fluentd
    context: fluentd

deploy:
  helm:
    releases:
    - name: '{{ .P2L_RELEASE }}'
      chartPath: helm
      skipBuildDependencies: true
      setValueTemplates:
        post2log.image.registry: '{{ .IMAGE_DOMAIN_post2log_server }}'
        post2log.image.repository: '{{ .IMAGE_REPO_NO_DOMAIN_post2log_server }}'
        post2log.image.tag: '{{ .IMAGE_TAG_post2log_server }}'
        post2log.image.digest: '{{ .IMAGE_DIGEST_post2log_server }}'
        fluentd.image.registry: '{{ .IMAGE_DOMAIN_post2log_fluentd }}'
        fluentd.image.repository: '{{ .IMAGE_REPO_NO_DOMAIN_post2log_fluentd }}'
        fluentd.image.tag: '{{ .IMAGE_TAG_post2log_fluentd }}'
        fluentd.image.digest: '{{ .IMAGE_DIGEST_post2log_fluentd }}'

profiles:
- name: dev 
  patches: 
  - op: add 
    path: /deploy/helm/releases/0/valuesFiles
    value: 
    - configs/dev.yaml
- name: local 
  patches: 
  - op: add 
    path: /deploy/helm/releases/0/valuesFiles
    value: 
    - configs/local.yaml