apiVersion: skaffold/v4beta3
kind: Config
build:
  local:
    push: true
    
  artifacts:
  - image: post2log
    context: server 
  - image: fluentd-kafka
    context: fluentd-kafka

manifests:
  helm:
    releases:
    - name: post2log
      chartPath: helm
      setValueTemplates:
        image.repository: "{{ .IMAGE_REPO_post2log }}"
        image.tag: "{{ .IMAGE_TAG_post2log }}"
        port: "{{ or .P2L_PORT 80 }}"
        nodePort: "{{ or .P2L_NODEPORT \"\" }}"
        endpoint: "{{ or .P2L_ENDPOINT \"/postback\" }}"
        logQueryParam: "{{ or .P2L_LOG_QUERYPARAM \"true\" }}"
        ingressAnnotations: "{{ or .P2L_INGRESS_ANNOT \"\" }}"
        workers: "{{ or .P2L_WORKERS 1 }}"
        replicas: "{{ or .P2L_REPLICAS 1 }}"
        storage: "{{ or .P2L_STORAGE \"4Gi\" }}"
        rotBytes: "{{ or .P2L_ROTBYTES \"10485760\" }}"
        rotBackups: "{{ or .P2L_ROTBACKUPS 5 }}"
        uvicorn.logLevel: "{{ or .P2L_UVICORN_LOGLEVEL \"debug\" }}"
        fluentd.storage: "{{ or .P2L_FLUENTD_STORAGE \"4Gi\" }}"
        fluentd.extraCfg: "{{ or .P2L_FLUENTD_EXTRACFG \"\" }}"

