apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "util.fullname" . }}-fluentd-cfg
data:
  fluentd.conf: |
    <source>
      @type tail
      path /data/*post2log-*_*.txt
      pos_file /fluentd-out/post2log.pos
      tag post2log
      path_key filename
      read_from_head false
      refresh_interval 5
      <parse>
        @type json
      </parse>
    </source>

    <filter post2log>
      @type record_transformer
      remove_keys filename
    </filter>

    <match post2log>
      @type rewrite_tag_filter
      <rule>
        key _path
        pattern ^/postback/(.+)$
        tag $1
      </rule>
    </match>
    
{{ include "util.tplvalues.render" (dict "value" .Values.fluentd.extraCfg "context" $) | indent 4 }}
    <match **>
      @type stdout
    </match>