apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "post2log.fullname" . }}-fluentd-cfg
data:
  fluentd.conf: |
    <source>
      @type tail
      path /data/{{ .Release.Name }}-post2log-*_*.txt
      pos_file /fluentd-out/{{ .Release.Name }}.pos
      tag post2log
      path_key filename
      read_from_head false
      refresh_interval 5
      <parse>
        @type json
      </parse>
    </source>

    <filter post2log>
      @type record_transformer
      remove_keys filename
      {{- with .Values.fluentd.duplicateFields }}
      enable_ruby
      <record>
      {{- range $old_key, $new_key := . }}
        "{{ $new_key }}" ${record["{{ $old_key }}"] if record.has_key?("{{ $old_key }}")}
      {{- end }}
      </record>
      {{- end }}
    </filter>

    <match post2log>
      @type rewrite_tag_filter
      <rule>
        key _path
        pattern ^/postback/(.+)$
        tag $1
      </rule>
    </match>
    
{{ include "post2log.tplvalues.render" (dict "value" .Values.fluentd.extraCfg "context" $) | indent 4 }}
    <match **>
      @type stdout
    </match>