apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "post2log.fullname" . }}-fluentd-cfg
data:
  fluentd.conf: |
    <source>
      @type tail
      path /data/{{ include "post2log.appname" . }}-post2log-*_*.txt
      pos_file /fluentd-out/post2log.pos
      tag {{ include "post2log.appname" . }}
      path_key filename
      read_from_head false
      refresh_interval 5
      <parse>
        @type json
      </parse>
    </source>

    <filter {{ include "post2log.appname" . }}>
      @type record_transformer
      remove_keys filename
    </filter>

    <match {{ include "post2log.appname" . }}>
      @type rewrite_tag_filter
      <rule>
        key _path
        pattern ^/postback/(.+)$
        tag $1
      </rule>
    </match>
    
{{ include "post2log.tplvalues.render" (dict "value" .Values.fluentd.extraCfg "context" $) | indent 4 }}
    <match **>
      @type stdout
    </match>