---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "post2log.fullname" . }}
spec:
  {{- if .Values.nodePort }}
  type: NodePort
  {{- end }}
  selector:
    app: {{ .Release.Name }}-post2log
  ports:
  - port: {{ .Values.port }}
    targetPort: 8000
    {{- if .Values.nodePort }}
    nodePort: {{ .Values.nodePort }}
    {{- end }}
