# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: {{ include "post2log.fullname" . }}
# spec:
#   capacity:
#     storage: {{ .Values.storage }}
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual
#   hostPath:
#     path: /data
#     type: DirectoryOrCreate
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ include "post2log.fullname" . }}
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: {{ .Values.storage }}
#   storageClassName: manual
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: {{ include "post2log.fullname" . }}-fluentd-out
# spec:
#   capacity:
#     storage: {{ .Values.fluentd.storage }}
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual
#   hostPath:
#     path: /fluentd-out
#     type: DirectoryOrCreate
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ include "post2log.fullname" . }}-fluentd-out
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: {{ .Values.fluentd.storage }}
#   storageClassName: manual
