apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "tmp.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tmp.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "tmp.fullname" . }}-fluentd-out-pv
spec:
  capacity:
    storage: {{ .Values.fluentd.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /fluentd-out
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tmp.fullname" . }}-fluentd-out-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.fluentd.storage }}
  storageClassName: manual
