# (anly 로 설치된) abmon 과 연동 개발 
nodeExclusive: false
ingress:
  enabled: true
replicas: 1
fluentd: 
  extraCfg: |
    <match {{ .Release.Name }}> 
      @type influxdb
      host anly-influxdb
      port 8086
      dbname post2log
      user admin
      password admindjemals
      time_precision ns
      use_ssl false
      <buffer>
        @type memory
        chunk_limit_size 1m
        flush_mode interval
        flush_interval 10
      </buffer>
    </match>

    # <system>
    #   log_level trace
    # </system>
