# Helm 차트 디버깅을 위한 기본값
image: 
  repository: docker.io/haje01/post2log
  tag: latest
port: 80
nodePort: ""
nodeRole: ""
endpoint: /postback
logQueryParam: true
ingressAnnotations: ""
workers: 1
replicas: 1
storage: 4Gi
rotBytes: 10485760
rotBackups: 5
uvicorn:
  logLevel: debug
fluentd:
  storage: 4Gi
  extraCfg: ""
