# Helm 차트 디버깅을 위한 기본값
post2log:
  image: docker.io/haje01/post2log:latest
fluentd:
  image: docker.io/haje01/post2log_fluentd:latest
  storage: 4Gi
  extraCfg: |
    <match test>
      # Helm 변수 참조 테스트
      # Release Name : {{ .Release.Name }}
      @type stdout
    </match>"
port: 80
nodePort: ""
nodeSelector: ""
endpoint: /postback/test
logQueryParam: true
skipNullFields: true
ingressAnnotations: ""
workers: 1
replicas: 1
storage: 4Gi
rotBytes: "10485760"
rotBackups: 5
uvicorn:
  logLevel: debug
